### ISSUE TITLE
unable to install go-unit-report

### ISSUE THREAD

**Issue by kulninja** [jstemmer/go-junit-report#149] opened 2022-10-28 20:58 UTC
unaikku@SFCAWL-9123C6F:~/tfenv/golang-ecs$ go get github.com/jstemmer/go-junit-report
go: finding github.com/jstemmer/go-junit-report v1.0.0
go: downloading github.com/jstemmer/go-junit-report v1.0.0
go: extracting github.com/jstemmer/go-junit-report v1.0.0
**go get github.com/jstemmer/go-junit-report: rename /home/unaikku/go/pkg/mod/github.com/jstemmer/go-junit-report@v1.0.0.tmp-054416498 /home/unaikku/go/pkg/mod/github.com/jstemmer/go-junit-report@v1.0.0: permission denied**

**Comment by kulninja** [comment] 2022-10-28 20:59
Also - 

unaikku@SFCAWL-9123C6F:~/tfenv/golang-ecs$ go install github.com/jstemmer/go-junit-report/v2@latest
can't load package: package github.com/jstemmer/go-junit-report/v2@latest: **can only use path@version syntax with 'go get'**

**Comment by jstemmer** [comment] 2022-11-01 00:17
Can you provide some more details about your environment? What OS, what version of Go, etc.

**Comment by jstemmer** [comment] 2022-11-11 00:36
If you're running an older version of Go, you can try to update to a later version. I'm not able to reproduce this. Without more information it's hard to say what the problem is, so I'm closing this issue. Feel free to reopen this if you can share more about your environment.

**Closed by jstemmer** 2022-11-11 00:36 UTC
